### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Veerhan-glitch**
Solves #1 
also can you pls add hacktoberfest-accepted label to the pr if you decided to merge this

### CODE REVIEW

**Comment by yashchaudhari008** [comment]
Could you refer to my other repo and follow the same structure for README.md

**Comment by Veerhan-glitch** [comment]
ya sure will also do that

**Comment by Veerhan-glitch** [comment]
hi can you pls add hacktoberfest-accepted label to the pr as currently it is showing as 'NOT-PARTICIPATING'
thx

**Comment by yashchaudhari008** [comment]
Sure, I will do it asap 👍 and also review and merge.

**Comment by yashchaudhari008** [comment]
Did you make changes according to README of my other projects?

**Comment by yashchaudhari008** [comment]
> Yea about that i will do that when I get time as I am going to be pretty busy for some months now. But dw I will keep working on that even after October. Sorry for the inconvenience.

You were going to work on it!

**Comment by Veerhan-glitch** [comment]
I said I will work on the other repo readme, wasn't this repo redme done? (The reason I closed)

And for the other I will prob do around June as I have colage entrence exams.

**Pull request closed without merging**
